FlightReservationSystem(MVC)/Controllers/UserHomeController.cs
using FlightReservationSystem_MVC_.Data;
using FlightReservationSystem_MVC_.Models;
using Microsoft.AspNetCore.Mvc;

namespace FlightReservationSystem_MVC_.Controllers
{
    public class UserHomeController : Controller
    {
        private readonly ApplicationDbContext _db;
        public User _user = new Models.User();

        public string _email="email";
        public UserHomeController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index(User user)
        {
            ViewBag.email = user.email;
            //=================change
            //return RedirectToAction("ViewFlight", user);
            return View();
        }

        /*public IActionResult Index(string email)
        {
            ViewBag.email = email;
            //=================change
            //return RedirectToAction("ViewFlight", user);
            return View();
        }*/

        /*public IActionResult ViewFlight(User user)
        {
            _user = user;
            IEnumerable<Flight> objFlightList = _db.FlightDetails;
            ViewBag.email = _user.email;
            return View(objFlightList);
        }*/

        public IActionResult Book(string? id, string? email)
        {
            if (id == null || email == null)
            {
                return NotFound();
            }
            _email= email;
            var userDetails = _db.User.Find(email);
            var flightDB = _db.FlightDetails.Find(id);
            Booking book = new Booking
            {
                flightid = id,
                name = flightDB.name,
                source = flightDB.source,
                destination = flightDB.destination,
                hours = flightDB.hours,
                seats = flightDB.seats,
                days = flightDB.days,
                cost = flightDB.cost,
                email = email,
                FName = userDetails.FName,
                LName = userDetails.LName,
                dob = userDetails.dob,
                gender = userDetails.gender,
                address = userDetails.address,
                password = userDetails.password,
                pno = userDetails.pno,
            };
            if (flightDB == null || userDetails == null)
            {
                return NotFound();
            }
            return View(book);
        }

        public IActionResult BookConfirm(string? id, string? email)
        {
            if (id == null || email == null)
            {
                return NotFound();
            }
            var userDetails = _db.User.Find(email);
            var flightDB = _db.FlightDetails.Find(id);
            Booking book = new Booking
            {
                flightid = id,
                name = flightDB.name,
                source = flightDB.source,
                destination = flightDB.destination,
                hours = flightDB.hours,
                seats = flightDB.seats,
                days = flightDB.days,
                cost = flightDB.cost,
                email = email,
                FName = userDetails.FName,
                LName = userDetails.LName,
                dob = userDetails.dob,
                gender = userDetails.gender,
                address = userDetails.address,
                password = userDetails.password,
                pno = userDetails.pno,
            };
            _db.Booking.Add(book);
            _db.SaveChanges();
            return RedirectToAction("ViewBooking", book);
            if (flightDB == null || userDetails == null)
            {
                return NotFound();
            }
            return RedirectToAction("ViewFlight", book);
        }

        /*public IActionResult ViewBooking(Booking book)
        {
            bool userExist = _db.Booking.Any(x => x.email == book.email);
            Booking userBooking = _db.Booking.FirstOrDefault(x => x.email == book.email);
            IEnumerable<Booking> objBookingList = _db.Booking;
            return View(objBookingList);
        }*/

        public IActionResult Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var booking = _db.Booking.Find(id);
            if (booking == null)
            {
                return NotFound();
            }
            return View(booking);
        }

        public IActionResult DeletePOST(int id)
        {
            var obj = _db.Booking.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.Booking.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("ViewBooking", obj);
        }








        //=======================================================================
        //New
        public IActionResult ViewFlight(string email)
        {
            IEnumerable<Flight> objFlightList = _db.FlightDetails;
            ViewBag.email = email;
            return View(objFlightList);
        }

        public IActionResult ViewBooking(string email)
        {
            bool userExist = _db.Booking.Any(x => x.email == email);
            ViewBag.email = email;
            Booking userBooking = _db.Booking.FirstOrDefault(x => x.email == email);
            IEnumerable<Booking> objBookingList = _db.Booking;
            return View(objBookingList);
        }

    }
}

FlightReservationSystem(MVC)/Views/UserHome/Book.cshtml
@model Booking
@{
    Layout = "_UserLayout";
}
<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Flight Id@*@Html.DisplayNameFor(model => model.flightid)*@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.flightid)
        </dd>

        <dt class = "col-sm-2">
            Flight Name@*@Html.DisplayNameFor(model => model.name)*@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt class = "col-sm-2">
            Source@*@Html.DisplayNameFor(model => model.source)*@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.source)
        </dd>
        <dt class = "col-sm-2">
            Destination@*@Html.DisplayNameFor(model => model.destination)*@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.destination)
        </dd>
        <dt class = "col-sm-2">
            Traveller's First Name
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FName)
        </dd>
        <dt class = "col-sm-2">
            Traveller's Last Name@*@Html.DisplayNameFor(model => model.LName)*@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LName)
        </dd>
    </dl>
</div>

<div>
    <div>
        <a asp-controller="UserHome" asp-action="BookConfirm" asp-route-id="@Model.flightid" asp-route-email="@Model.email" class="btn btn-primary" style="width:150px">
            Book Flight
        </a>
    </div>
    <br />
    <div class="col-3">
	    <a asp-controller="UserHome" asp-action="Index" asp-route-email="@Model.email" class="btn btn-success" style="width:150px">
		    <i class="bi bi-house-fill"></i>
            Home
	    </a>
    </div>
</div>

FlightReservationSystem(MVC)/Views/UserHome/Delete.cshtml
@model Booking
@{
    Layout = "_UserLayout";
}
<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Flight Id@*@Html.DisplayNameFor(model => model.flightid)*@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.flightid)
        </dd>

        <dt class = "col-sm-2">
            Flight Name@*@Html.DisplayNameFor(model => model.name)*@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt class = "col-sm-2">
            Source@*@Html.DisplayNameFor(model => model.source)*@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.source)
        </dd>
        <dt class = "col-sm-2">
            Destination@*@Html.DisplayNameFor(model => model.destination)*@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.destination)
        </dd>
        <dt class = "col-sm-2">
            Traveller's First Name
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FName)
        </dd>
        <dt class = "col-sm-2">
            Traveller's Last Name@*@Html.DisplayNameFor(model => model.LName)*@
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LName)
        </dd>
    </dl>
</div>

<div>
    <div>
        <a asp-controller="UserHome" asp-action="DeletePOST" asp-route-id="@Model.BookingId" class="btn btn-danger" style="width:150px">
            Cancel Flight
        </a>
    </div>
    <br />
    <div class="col-3">
	    <a asp-controller="UserHome" asp-action="Index" asp-route-email="@Model.email" class="btn btn-secondary" style="width:150px">
		    <i class="bi bi-house-fill"></i>
            Home
	    </a>
    </div>
</div>

FlightReservationSystem(MVC)/Views/UserHome/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_UserLayout";
}
@model User
<h1>
    Welcome @ViewBag.email
</h1>
<a asp-controller="UserHome" asp-action="ViewBooking" asp-route-email="@ViewBag.email" class="btn btn-primary" style="font-size:small; height:30px">
    View Bookings
</a>
<a asp-controller="UserHome" asp-action="ViewFlight" asp-route-email="@ViewBag.email" class="btn btn-success" style="font-size:small; height:30px">
    View Flights
</a>

FlightReservationSystem(MVC)/Views/UserHome/ViewBooking.cshtml
@*capture the model that we passed from category controller*@
@model IEnumerable<Booking>
@{
    ViewData["Title"] = "Index";
}
@{
    Layout = "_UserLayout";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Booking List</h2>
        </div>
    </div>

<table class="table table-bordered table-striped" style="width:100%; background: rgba(0, 0, 0, 0.3);">
    <thead>
        <tr>
            <th>
                Flight Id
            </th>
            <th>
                Flight Name
            </th>
            <th>
                Source
            </th>
            <th>
                Destination
            </th>
            <th>
                Cost
            </th>
            <th>
                Name
            </th>
            <th>
                Cancel Booking
            </th>
        </tr>
    </thead>
    <tbody>
        @*iterate through all of the properties in the model*@
        @foreach(var obj in Model)
        {
                if (obj.email == @ViewBag.email)
                {

                    <tr style="text-align:center">
                        <td width=10%>
                            @obj.flightid
                        </td>
                        <td width=10%>
                            @obj.name
                        </td>
                        <td width=10%>
                            @obj.source
                        </td>
                        <td width=10%>
                            @obj.destination
                        </td>
                        <td width=10%>
                            @obj.cost
                        </td>
                        <td width=10%>
                            @obj.FName @obj.LName
                        </td>
                        <td>
                            <a asp-controller="UserHome" asp-action="Delete" asp-route-id="@obj.BookingId" class="btn btn-danger" style="font-size:small; height:30px">
                                <i class="bi bi-trash-fill"></i>
                                Delete
                            </a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
    <a asp-controller="UserHome" asp-action="Index" asp-route-email="@ViewBag.email" class="btn btn-success" style="font-size:small; height:30px">
        <i class="bi bi-house-fill"></i>
	    Home
    </a>
</div>

FlightReservationSystem(MVC)/Views/UserHome/ViewFlight.cshtml
@*capture the model that we passed from category controller*@
@model IEnumerable<Flight>
@{
    ViewData["Title"] = "Index";
}
@{
    Layout = "_UserLayout";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Flight List</h2>
        </div>
    </div>

<table class="table table-bordered table-striped" style="width:100%; background: rgba(0, 0, 0, 0.3);">
    <thead>
        <tr>
            <th>
                Flight Id
            </th>
            <th>
                Flight Name
            </th>
            <th>
                Source
            </th>
            <th>
                Destination
            </th>
            <th>
                Hours
            </th>
            <th>
                Seats
            </th>
            <th>
                Days
            </th>
            <th>
                Cost
            </th>
            <th>
                Book Flight
            </th>
        </tr>
    </thead>
    <tbody>
        @*iterate through all of the properties in the model*@
        @foreach(var obj in Model)
        {
            <tr style="text-align:center">
                <td width=10%>
                    @obj.flightid
                </td>
                <td width=10%>
                    @obj.name
                </td>
                <td width=10%>
                    @obj.source
                </td>
                <td width=10%>
                    @obj.destination
                </td>
                <td width=10%>
                    @obj.hours
                </td>
                <td width=10%>
                    @obj.seats
                </td>
                <td width=10%>
                    @obj.days
                </td>
                <td width=10%>
                    @obj.cost
                </td>
                <td width=10%>
                    <a asp-controller="UserHome" asp-action="Book" asp-route-id="@obj.flightid" asp-route-email="@ViewBag.email" class="btn btn-secondary" style="font-size:small; height:30px">
                        <i class="bi bi-pencil-square"></i>
					    Book
				    </a>
                </td>
            </tr>
        }
        </tbody>
    </table>
    <a asp-controller="UserHome" asp-action="Index" asp-route-email="@ViewBag.email" class="btn btn-danger" style="font-size:small; height:30px">
        <i class="bi bi-house-fill"></i>
	    Home
    </a>
</div>