FlightReservationSystem(MVC)/Controllers/FlightController.cs
using FlightReservationSystem_MVC_.Data;
using FlightReservationSystem_MVC_.Models;
using Microsoft.AspNetCore.Mvc;

namespace FlightReservationSystem_MVC_.Controllers
{
    public class FlightController : Controller
    {
        private readonly ApplicationDbContext _db;
        public FlightController(ApplicationDbContext db)
        {
            this._db = db;
        }
        public IActionResult AddFlight()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddFlight(Flight obj)
        {
            //check if model is valid
            if (ModelState.IsValid)
            {
                _db.FlightDetails.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("UpdateFlight");
            }
            return View(obj);
        }

        public IActionResult UpdateFlight()
        {
            IEnumerable<Flight> objFlightList = _db.FlightDetails;
            return View(objFlightList);
        }

        public IActionResult Edit(string? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            var flightDB = _db.FlightDetails.Find(id);
            FlightEdit flightEdit  = new FlightEdit
            {
                flightid = id,
                name = flightDB.name,
                source = flightDB.source,
                destination = flightDB.destination,
                hours = flightDB.hours,
                seats = flightDB.seats,
                days = flightDB.days,
                cost = flightDB.cost,
            };
            if (flightDB == null)
            {
                return NotFound();
            }
            return View(flightEdit);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(FlightEdit obj)
        {
            //check if model is valid
            if (ModelState.IsValid)
            {
                var flightDB = _db.FlightDetails.Find(obj.flightid);
                flightDB.name = obj.name;
                flightDB.source = obj.source;
                flightDB.destination = obj.destination;
                flightDB.hours = obj.hours;
                flightDB.days = obj.days;
                flightDB.cost = obj.cost;
                flightDB.seats = obj.seats;
                _db.FlightDetails.Update(flightDB);
                _db.SaveChanges();
                return RedirectToAction("UpdateFlight");
            }
            return View(obj);
        }


        public IActionResult Delete(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var flightDB = _db.FlightDetails.Find(id);
            if (flightDB == null)
            {
                return NotFound();
            }
            return View(flightDB);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(string? flightid)
        {
            var obj = _db.FlightDetails.Find(flightid);
            if (obj == null)
            {
                return NotFound();
            }
            _db.FlightDetails.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("UpdateFlight");
        }
    }
}

FlightReservationSystem(MVC)/Controllers/RoutesController.cs
using FlightReservationSystem_MVC_.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FlightReservationSystem_MVC_.Controllers
{
    public class RoutesController : Controller
    {
        private readonly ApplicationDbContext _db;

        public RoutesController(ApplicationDbContext context)
        {
            _db = context;
        }

        public IActionResult Index()
        {
            IEnumerable<Models.Route> objRouteList = _db.Route;
            return View(objRouteList);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _db.Route == null)
            {
                return NotFound();
            }

            var route = await _db.Route
                .FirstOrDefaultAsync(m => m.RouteID == id);
            if (route == null)
            {
                return NotFound();
            }

            return View(route);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RouteID,FromRoute,ToRoute")] Models.Route route)
        {
            if (ModelState.IsValid)
            {
                _db.Add(route);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(route);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _db.Route == null)
            {
                return NotFound();
            }

            var route = await _db.Route.FindAsync(id);
            if (route == null)
            {
                return NotFound();
            }
            return View(route);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RouteID,FromRoute,ToRoute")] Models.Route route)
        {
            if (id != route.RouteID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _db.Update(route);
                    await _db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RouteExists(route.RouteID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(route);
        }

        // GET: Routes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _db.Route == null)
            {
                return NotFound();
            }

            var route = await _db.Route
                .FirstOrDefaultAsync(m => m.RouteID == id);
            if (route == null)
            {
                return NotFound();
            }

            return View(route);
        }

        // POST: Routes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_db.Route == null)
            {
                return Problem("Entity set 'RouteDetails1Context.Route'  is null.");
            }
            var route = await _db.Route.FindAsync(id);
            if (route != null)
            {
                _db.Route.Remove(route);
            }

            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RouteExists(int id)
        {
            return (_db.Route?.Any(e => e.RouteID == id)).GetValueOrDefault();
        }
    }
}

FlightReservationSystem(MVC)/Controllers/UserController.cs
using FlightReservationSystem_MVC_.Data;
using FlightReservationSystem_MVC_.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient; 
using System.Configuration;

namespace FlightReservationSystem_MVC_.Controllers
{
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _db;
        public UserController(ApplicationDbContext db)
        {
            this ._db = db;
        }
        public IActionResult Index()
        {
            return View();
        }

        //GET
        public IActionResult Signup()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Signup(User obj)
        {
            //check if model is valid
            if (ModelState.IsValid)
            {
                _db.User.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Login");
            }
            return View(obj);
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login(User obj)
        {
            bool userExist = _db.User.Any(x => x.email == obj.email && x.password == obj.password);
            User user = _db.User.FirstOrDefault(x => x.email == obj.email && x.password == obj.password);
            if (userExist)
            {
                if(user.email == "admin@gmail.com")
                {
                    return RedirectToAction("Index", "Admin");
                }
                string email=obj.email;
                //change=============================== user to user.email
                return RedirectToAction("Index", "UserHome", user);
            }
            ModelState.AddModelError("", "Username or password does not match");
            return View();
        }
    }
}

FlightReservationSystem(MVC)/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FlightReservationSystem_MVC_</title>
    <link rel="stylesheet" href="~/css/BootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FlightReservationSystem_MVC_.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" />

    <style>
        .flight-image {
          background-image: url("https://c1.wallpaperflare.com/preview/929/926/321/plane-sunset-sunrise-wing.jpg");
          background-color: #cccccc;
          height: 1000px ;
          background-position: center;
          background-repeat: no-repeat;
          background-size: cover;
          position: relative;
          /*background-blend-mode: darken;*/
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Flight Reservation</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link" asp-area="" asp-controller="Flight" asp-action="AddFlight">Add Flight</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" asp-area="" asp-controller="Flight" asp-action="UpdateFlight">View Flight</a>
        </li>
        <li>
            <a class="nav-link" asp-area="" asp-controller="Routes" asp-action="Create">Add Route</a>
        </li>
        <li>
            <a class="nav-link" asp-area="" asp-controller="Routes" asp-action="Index">View Route</a>
        </li>
        </ul>
        <li class="nav-item" style="list-style: none; margin-left: 20px;">
          <a class="btn btn-outline-dark" style="width:100px" asp-area="" asp-controller="Home" asp-action="Index">Signout</a>
        </li>
    </div>
  </div>
</nav>
    </header>
    <div class="flight-image">
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
  </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - FlightReservationSystem_MVC_ - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    
</body>
</html>

FlightReservationSystem(MVC)/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FlightReservationSystem_MVC_</title>
    <link rel="stylesheet" href="~/css/BootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FlightReservationSystem_MVC_.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" />

    <style>
        .flight-image {
          background-image: url("https://c1.wallpaperflare.com/preview/929/926/321/plane-sunset-sunrise-wing.jpg");
          background-color: #cccccc;
          height: 1000px ;
          background-position: center;
          background-repeat: no-repeat;
          background-size: cover;
          position: relative;
          /*background-blend-mode: darken;*/
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Flight Reservation</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link active" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </li>
        @*<li class="nav-item">
          <a class="nav-link" asp-area="" asp-controller="Flight" asp-action="AddFlight">Add Flight</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" asp-area="" asp-controller="Flight" asp-action="UpdateFlight">View Flight</a>
        </li>
        <li>
            <a class="nav-link" asp-area="" asp-controller="Routes" asp-action="Index">Route Details</a>
        </li>*@
        </ul>
        <li class="nav-item" style="list-style: none; margin-left: 20px;">
          <a class="btn btn-outline-light" style="width:100px" asp-area="" asp-controller="User" asp-action="Login">Login</a>
        </li>
        <li class="nav-item" style="list-style: none; margin-left: 20px;">
          <a class="btn btn-outline-dark" style="width:100px" asp-area="" asp-controller="User" asp-action="Signup">Signup</a>
        </li>
    </div>
  </div>
</nav>
    </header>
    <div class="flight-image">
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
  </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - FlightReservationSystem_MVC_ - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    
</body>
</html>

FlightReservationSystem(MVC)/Views/Shared/_UserLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FlightReservationSystem_MVC_</title>
    <link rel="stylesheet" href="~/css/BootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FlightReservationSystem_MVC_.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" />

    <style>
        .flight-image {
          background-image: url("https://c1.wallpaperflare.com/preview/929/926/321/plane-sunset-sunrise-wing.jpg");
          background-color: #cccccc;
          height: 1000px ;
          background-position: center;
          background-repeat: no-repeat;
          background-size: cover;
          position: relative;
          /*background-blend-mode: darken;*/
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Flight Reservation</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
        @*<li class="nav-item">
          <a class="nav-link" asp-area="" asp-controller="UserHome" asp-action="ViewFlight">View Flight</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" asp-area="" asp-controller="UserHome" asp-action="ViewBooking">View Booking</a>
        </li>*@
        </ul>
        <li class="nav-item" style="list-style: none; margin-left: 20px;">
          <a class="btn btn-outline-dark" style="width:100px" asp-area="" asp-controller="Home" asp-action="Index">Signout</a>
        </li>
    </div>
  </div>
</nav>
    </header>
    <div class="flight-image">
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
  </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - FlightReservationSystem_MVC_ - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    
</body>
</html>